[project]
name = "day13-k3-observability"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "ashura102938475", email = "tra01020407@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.118.0",
    "httpx==0.28.1",
    "opentelemetry-api>=1.44.0",
    "opentelemetry-exporter-otlp>=1.44.0",
    "opentelemetry-instrumentation-fastapi>=0.65b0",
    "opentelemetry-sdk>=1.44.0",
    "prometheus-client>=0.26.0",
    "pydantic==2.11.4",
    "pytest==8.3.5",
    "python-dotenv==1.1.0",
    "pyyaml==6.0.3",
    "structlog==25.4.0",
    "uvicorn[standard]==0.37.0",
]


